export const Expdata = [
  {
    id: 0,
    indicator: "2022 P.G Graduated",
    year1: "",
    title1: "",
    levelOfEd: "",
    grade: "",
    text1: "",
    year2: "Sept 2022 - Present",
    company: "The Co-operators",
    title2: "Full Stack Developer - Contract Full-Time",
    text2:
      "• Built responsive Web design components in React.js on Typescript and JavaScript and designed data models and API endpoints to connect to the database. • Designed and implemented data models in Node.js, MySQL and PostgreSQL as the database. • Good coding standards include documentation for the features developed, logging results of the API request, following TDD (Test Driven Development), and documentationSkills: React.js • JavaScript • Node.js • Responsive Web Design • PostgreSQL • SQL",
  },
  {
    id: 1,
    indicator: "2022",
    year1: "",
    title1: "",
    levelOfEd: "",
    grade: "",
    text1: "",
    year2: "May 2022 - Aug 2022",
    company: "The Co-operators",
    title2: "Full Stack Developer - Co-op",

    text2:
      "• Experienced in understanding client requirements, following Agile methodologies, Scrum, providing Prod support, and using Splunk to monitor the data in Production. • Good command of writing unit and integration tests for the developed features. • Bi-weekly, we will have an incubator day on which we spend all day learning new technologies and demoing what we learned to everyone by the end of the day.",
  },
  {
    id: 2,
    indicator: "2022",
    year1: "",
    title1: "",
    levelOfEd: "",
    grade: "",
    text1: "",
    year2: "Feb 2022 - Apr 2022",
    company: "Suvidha Foundation",
    title2: "Web Developer - Internship",
    text2:
      "I have trained more than 10 interns in Web development using ReactJS. • I have been a part of the User experience team to understand the client needs and designed the UI for the Online education platform. • I have been a part of setting standards in initial project creation and development. I have been a part of the User experience team to understand the client needs and designed the UI for the Online education platform.",
  },
  {
    id: 3,
    indicator: "2021",
    year1: "Sep 2021 - Dec 2022",
    title1: "Conestoga College",
    levelOfEd: "Post Graduate Program - Embedded Systems Development",
    grade: "3.9 GPA",
    text1: "I have completed Post Graduation Diploma in the Embedded systems development program with distinction. In this course, · I have learned Assembly level Programming. · Always stood in the top 3 in the class and actively participated in the Student games club.",
    year2: "Nov 2021 - Present",
    company: "Varsity Tutors",
    title2: "Coding Instructor - Part-Time",
    text2:
      "I wanted to share my knowledge of software development with more people. This made me invest time in teaching as a coding instructor at Varsity tutors. • I have a 5-star rating on my profile, proving that my students are delighted with my classes. • My teaching group includes teenagers, real software developers, and computer science grads seeking knowledge.",
  },
  {
    id: 4,
    indicator: "2021",
    year1: "",
    title1: "",
    levelOfEd: "",
    grade: "",
    text1: "",
    year2: "Dec 2020 - Jul 2021",
    company: "Nineleaps",
    title2: "Frontend Developer - Full-Time",
    text2:
      " • Worked as a mobile app developer for two projects at Nineleaps. • Increased the sprint velocity by 20% and maintained it till the project completion. • Was awarded as the best employee in May. • Been a part of developing features and functionality of an NPM package for a project. • Developed a “StackOverflow duplicate mobile app” as an internal project which could be accessible to only Nineleaps employees to share their knowledge and help each other in problem-solving.",
  },
  {
    id: 5,
    indicator: "2020 B.E Graduated",
    year1: "",
    title1: "",
    levelOfEd: "",
    grade: "",
    text1: "",
    year2: "Mar 2019 - Nov 2020",
    company: "Freelancer",
    title2: "Freelance Software Developer",
    text2:
      "After my placement at the start of my final year, I started developing web and mobile apps for my clients and my own websites. • React Native - Mobile apps android & IOS • React.Js - Web apps",
  },
  {
    id: 6,
    indicator: "2019",
    year1: "",
    title1: "",
    levelOfEd: "",
    grade: "",
    text1: "",
    year2: "May 2019 - Jun 2019",
    company: "SAMEER (R&D of DIT)",
    title2: "Student Intern",
    text2:
      "• As a trainee, I worked on a project of specially designed DOPPLER RADAR made of Horn antennas that can track the speed of raindrops with a graduate pursuing student. • Filtered out the noise from the mixed input signal and obtained the filtered frequency signal to estimate the speed of the moving object. • Learned FEKO software for antenna designing and testing.",
  },
  {
    id: 7,
    indicator: "2018",
    year1: "",
    title1: "",
    levelOfEd: "",
    grade: "",
    text1: "",
    year2: "May 2018 - Jun 2018",
    company: "Visakhapatnam Steel Plant RINL",
    title2: "Student Intern",
    text2:
      "• Trained on working of SCADA(Supervisory Control And Data Acquisition) and IPVM(Internet Protocol Video Monitoring). • Checking the communication lines and reporting the issues to senior Electronic engineers. • Trained on maintaining Net Server.",
  },
  {
    id: 8,
    indicator: "2016",
    year1: "May 2016 - Apr 2020",
    title1: "Anil Neerukonda Institute of Technology & Sciences",
    levelOfEd: "Bachelor of Technology",
    grade: "Grade: 3.9 GPA",
    text1:
      "I have completed a Bachelor of Technology in Electronics and Communications Engineering with distinction. In this course,• I have learned the programming languages such as C, C++, JavaScript, and Python. • Secured several awards in hackathons.• Been an NSS team leader for 2 years • Been an active participant in cultural and volunteer work.• Started Help Youth Organization to help the needy.",
    year2: "",
    title2: "",
    text2: "",
  },
];
